# Generated by Django 5.1.4 on 2025-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_tag_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
